import type { Metadata } from "next";
import { headers } from "next/headers";
import ContextProvider from "@/provider/AppProvider";
import "./globals.css";
export const metadata: Metadata = {
  title: "NOVAA",
  description: "Generated by create monad dapp",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersData = await headers();
  const cookies = headersData.get("cookie");
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ContextProvider cookies={cookies}>{children}</ContextProvider>
      </body>
    </html>
  );
}
